# NSE Strategy configuration
# Fill in your parameters here 

# NSE Intraday Options Strategy Config

# Strategy parameters
instrument_id: NIFTY.OPT.03Jul2025.22800.CALL.NSE

# Required for modular runner
start_time: "2025-06-18T09:15:00"
end_time: "2025-06-20T15:30:00"

sl_pct: 0.02  # legacy, not used in new logic
tp_pct: 0.03
# atm_window: "15min"
position_size: 1
# entry_buffer_pct:  0.1
# lookback_intervals:  4
# min_iv: float = 25
min_iv: 0.0
min_oi_change: 0.0
# min_iv: 25.0
entry_buffer_pct: 0.1
lookback_intervals: 4
breakeven_trigger_pct: 2
sar_enabled: true
catalog_path: "catalog-data/my_nse_strategy/catalog"
meta_catalog_path: "catalog-data/my_nse_strategy/catalog-meta"