source_csv: "data/futures/YF/nifty50_1year_complete.csv"
destination_catalog: "catalog-data/nd_tt_v4/catalog"
destination_meta: "catalog-data/nd_tt_v4/catalog-meta"

# Data description
data_kind: bar
bar_interval: "1-DAY"

# Instrument metadata
symbol: NIFTY
venue: NSE
price_precision: 2
price_increment: 0.05
multiplier: 50

# Extra meta fields
extra_meta_fields:
  - Volume
  - Total_OI